### PR TITLE
Fixed #13552: Overwriting columns with the same alias

### LINKED ISSUE #13552: Paginator\Adapter\QueryBuilder Column not found: 1054 Unknown column in 'having clause'
When using `Paginator\Adapter\QueryBuilder` with multiple groups of fields with the same column name, the following behavior occurs

`GROUP BY vc.id, se.id, vc.zip, pc.id`

becomes 

`pc.id AS id, vc.zip AS zip`

in the totalBuilder count query witch results in an unkonwn column exception.

I think the solution would be to define an alias for all fields when building the [groupColumn ](https://github.com/phalcon/cphalcon/blob/399057545e2b9111871573a8e2a7944bf2e17958/phalcon/paginator/adapter/querybuilder.zep#L208)

### PR DESCRIPTION
**Pull request by CameronHall**
Hello!

* Type: bug fix
* Link to issue: #13552 

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: Fixed `Phalcon\Mvc\Model\Query::_prepareSelect` overwriting columns with the same alias. This specific issue only appeared when you were selecting columns across 
different tables with the same column name. The generated alias didn't factor in the different tables and any columns with the same name would get overridden. 

Take this example from `Phalcon\Test\Integration\Paginator\Adapter::testIssue13552`. This snippet would generate the SQL below when the paginator tries to find out the total items.
```php
$builder = $modelsManager->createBuilder()
    ->columns("Robots.*")
    ->from(['Robots' => Robots::class])
    ->join(RobotsParts::class, "RobotsParts.robots_id = Robots.id", "RobotsParts", "LEFT")
    ->join(RobotsParts::class, "RobotsParts_2.robots_id = Robots.id", "RobotsParts_2", "LEFT")
    ->groupBy('Robots.id, RobotsParts.id, RobotsParts.parts_id, RobotsParts_2.id, RobotsParts_2.parts_id')
    ->having('Robots.id > 2');

$paginate = (new QueryBuilder([
    "builder" => $builder,
    "limit"   => 1,
    "page"    => 2
]))->paginate();
```

Before:
```sql
SELECT DISTINCT 
    `RobotsParts_2`.`id` AS `id`,
     `RobotsParts_2`.`parts_id` AS `parts_id`
FROM `robots` AS `Robots`
LEFT JOIN `robots_parts` AS `RobotsParts` 
    ON `RobotsParts`.`robots_id` = `Robots`.`id`
LEFT JOIN `robots_parts` AS `RobotsParts_2` 
    ON `RobotsParts_2`.`robots_id` = `Robots`.`id`
GROUP BY
   `Robots`.`id`,
   `RobotsParts`.`id`,
   `RobotsParts`.`parts_id`,
   `RobotsParts_2`.`id`,
   `RobotsParts_2`.`parts_id`
HAVING `Robots`.`id` > 2
```

After:
```sql
SELECT DISTINCT 
    `Robots`.`id` AS `Robots_id`,
    `RobotsParts`.`id` AS `RobotsParts_id`,
    `RobotsParts`.`parts_id` AS `RobotsParts_parts_id`,
    `RobotsParts_2`.`id` AS `RobotsParts_2_id`,
    `RobotsParts_2`.`parts_id` AS `RobotsParts_2_parts_id`
FROM `robots` AS `Robots`
LEFT JOIN `robots_parts` AS `RobotsParts` 
    ON `RobotsParts`.`robots_id` = `Robots`.`id`
LEFT JOIN `robots_parts` AS `RobotsParts_2` 
    ON `RobotsParts_2`.`robots_id` = `Robots`.`id`
GROUP BY
   `Robots`.`id`,
   `RobotsParts`.`id`,
   `RobotsParts`.`parts_id`,
   `RobotsParts_2`.`id`,
   `RobotsParts_2`.`parts_id`
```

Thanks

### CODE REVIEW

File: tests/integration/Paginator/Adapter/QueryBuilderCest.php [hunk 1]
```diff
@@ -177,14 +177,12 @@ public function testIssue13552(IntegrationTester $I)
...
         $builder = $modelsManager->createBuilder()
-            ->columns("COUNT(*) as robos_count")
+            ->columns("Robots.*")
             ->from(['Robots' => Robots::class])
             ->join(RobotsParts::class, "RobotsParts.robots_id = Robots.id", "RobotsParts", "LEFT")
             ->join(RobotsParts::class, "RobotsParts_2.robots_id = Robots.id", "RobotsParts_2", "LEFT")
             ->groupBy('Robots.id, RobotsParts.id, RobotsParts.parts_id, RobotsParts_2.id, RobotsParts_2.parts_id')
-            ->having('MAX(Robots.year) > 1970');
-
-        // var_dump($builder->getQuery()->getSql());
```
Comment (sergeyklay) [inline tests/integration/Paginator/Adapter/QueryBuilderCest.php]: :heart:

**Comment by niden** [comment]
@CameronHall Something wrong with the tests bud.
