### PR TITLE
Changed return type hint for Model::getEventsManager

### LINKED ISSUE #15008: [BUG]:  Incorrect return type hint of Phalcon\Mvc\Model::getEventsManager()
The current implementation of `Phalcon\Mvc\Model::getEventsManager` implies that method must return a `Phalcon\Events\ManagerInterface` instance:
https://github.com/phalcon/cphalcon/blob/930fc080a70ef3a77da2df2753c3814c738ed475/phalcon/Mvc/Model.zep#L1702-L1705

however, `Manger::getCustomEventsManager` may return boolean FALSE:
https://github.com/phalcon/cphalcon/blob/3691c7fa77c92945f5a2c03beca4e32e2d8c30ec/phalcon/Mvc/Model/Manager.zep#L199-L208

This leads to a fatal error:
```
PHP Fatal error:
Return value of Phalcon\Mvc\Model::getEventsManager()
must implement interface Phalcon\Events\ManagerInterface,
bool returned in Unknown on line 0
```

### PR DESCRIPTION
**Pull request by sergeyklay**
Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/cphalcon/issues/15008

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

- Changed return type hint for `Phalcon\Mvc\Model\Manager::getCustomEventsManager` to return NULL instead of boolean FALSE if there is no special events manager
- Fixed return type hint for `Phalcon\Mvc\Model::getEventsManager` to reflect original behavior

Thanks

### CODE REVIEW

File: tests/database/Mvc/Model/GetSetEventsManagerCest.php [hunk 1]
```diff
@@ -28,20 +29,48 @@ class GetSetEventsManagerCest
...
+
+    /**
+     * Executed after each test
+     *
+     * @param  DatabaseTester $I
+     * @return void
+     */
+    public function _after(DatabaseTester $I): void
+    {
+        if ($this->invoiceMigration) {
```
Comment (niden) [inline tests/database/Mvc/Model/GetSetEventsManagerCest.php:64]: Not needed. `clear` is called the minute the migration object is created

**Review by niden — CHANGES_REQUESTED** [review]
One minor change

**Review by niden — APPROVED** [review]
